apiVersion: apps/v1
kind: Deployment
metadata:
  name: uba-frontend
  labels:
    app: uba
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uba
      tier: frontend
  template:
    metadata:
      labels:
        app: uba
        tier: frontend
    spec:
      containers:
      - name: uba-frontend
        image: uba-frontend:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://uba-backend:8080/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 