global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'uba-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['uba-backend:8080']
  
  - job_name: 'uba-frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['uba-frontend:80']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 